# ========================================================
# Core dependencies
# ========================================================
channels:
  - tensorflow
  - conda-forge

dependencies:
  - python>=3.9,<3.10

  # Open source packages
  - pandas=1.4.*
  - scikit-learn=1.0.*
  - numpy=1.24.*
  - pyyaml=6.0.*
  - seaborn=0.11.*
  - matplotlib=3.4.*
  - nltk=3.6.*
  - imbalanced-learn=0.10.*
  - tensorflow=2.8.*
  - transformers==4.30.*
  - wordcloud==1.9.*
  - pip
  - pip:
    - dataframe-image==0.1.*
    
